# Generated by Django 3.2.6 on 2021-08-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210806_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.activity'),
        ),
    ]
