# Generated by Django 3.2.6 on 2021-08-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_submission_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.FloatField(null=True),
        ),
    ]
